/*
Developer API

At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  BankTransferApi,
  ITPApi,
  QRCodeApi,
  RecipientApi,
  TokenApi,
  WebhookApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { SqalaCustom } from "./client-custom";

export class Sqala extends SqalaCustom {
  readonly bankTransfer: BankTransferApi;
  readonly iTP: ITPApi;
  readonly qRCode: QRCodeApi;
  readonly recipient: RecipientApi;
  readonly token: TokenApi;
  readonly webhook: WebhookApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.bankTransfer = new BankTransferApi(configuration);
    this.iTP = new ITPApi(configuration);
    this.qRCode = new QRCodeApi(configuration);
    this.recipient = new RecipientApi(configuration);
    this.token = new TokenApi(configuration);
    this.webhook = new WebhookApi(configuration);
  }

}
