/*
Developer API

At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ItpListAllResponseDataInnerMetadataInner } from './itp-list-all-response-data-inner-metadata-inner';
import { ItpListAllResponseDataInnerPayer } from './itp-list-all-response-data-inner-payer';
import { ItpListAllResponseDataInnerSplitInner } from './itp-list-all-response-data-inner-split-inner';

/**
 * 
 * @export
 * @interface ItpListAllResponseDataInner
 */
export interface ItpListAllResponseDataInner {
    /**
     * 
     * @type {string}
     * @memberof ItpListAllResponseDataInner
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ItpListAllResponseDataInner
     */
    'code'?: string;
    /**
     * 
     * @type {string}
     * @memberof ItpListAllResponseDataInner
     */
    'type'?: string;
    /**
     * 
     * @type {number}
     * @memberof ItpListAllResponseDataInner
     */
    'amount'?: number;
    /**
     * 
     * @type {any}
     * @memberof ItpListAllResponseDataInner
     */
    'paidAmount'?: any;
    /**
     * 
     * @type {string}
     * @memberof ItpListAllResponseDataInner
     */
    'payload'?: string;
    /**
     * 
     * @type {ItpListAllResponseDataInnerPayer}
     * @memberof ItpListAllResponseDataInner
     */
    'payer'?: ItpListAllResponseDataInnerPayer;
    /**
     * 
     * @type {Array<ItpListAllResponseDataInnerSplitInner>}
     * @memberof ItpListAllResponseDataInner
     */
    'split'?: Array<ItpListAllResponseDataInnerSplitInner>;
    /**
     * 
     * @type {string}
     * @memberof ItpListAllResponseDataInner
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof ItpListAllResponseDataInner
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ItpListAllResponseDataInner
     */
    'processedAt'?: string;
    /**
     * 
     * @type {any}
     * @memberof ItpListAllResponseDataInner
     */
    'paidAt'?: any;
    /**
     * 
     * @type {any}
     * @memberof ItpListAllResponseDataInner
     */
    'failedAt'?: any;
    /**
     * 
     * @type {Array<ItpListAllResponseDataInnerMetadataInner>}
     * @memberof ItpListAllResponseDataInner
     */
    'metadata'?: Array<ItpListAllResponseDataInnerMetadataInner>;
}

