/*
Developer API

At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { QrCodeGenerateQrCodeRequestMetadataInner } from './qr-code-generate-qr-code-request-metadata-inner';
import { QrCodeGenerateQrCodeRequestPayer } from './qr-code-generate-qr-code-request-payer';
import { QrCodeGenerateQrCodeRequestSplitInner } from './qr-code-generate-qr-code-request-split-inner';

/**
 * 
 * @export
 * @interface ItpCreatePaymentInstructionRequest
 */
export interface ItpCreatePaymentInstructionRequest {
    /**
     * Unique identifier for the object in your system.
     * @type {string}
     * @memberof ItpCreatePaymentInstructionRequest
     */
    'code'?: string;
    /**
     * Amount in cents to be paid.
     * @type {number}
     * @memberof ItpCreatePaymentInstructionRequest
     */
    'amount': number;
    /**
     * 
     * @type {QrCodeGenerateQrCodeRequestPayer}
     * @memberof ItpCreatePaymentInstructionRequest
     */
    'payer': QrCodeGenerateQrCodeRequestPayer;
    /**
     * This object represents a list of recipients who will receive part of the payment.
     * @type {Array<QrCodeGenerateQrCodeRequestSplitInner>}
     * @memberof ItpCreatePaymentInstructionRequest
     */
    'split'?: Array<QrCodeGenerateQrCodeRequestSplitInner>;
    /**
     * Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     * @type {Array<QrCodeGenerateQrCodeRequestMetadataInner>}
     * @memberof ItpCreatePaymentInstructionRequest
     */
    'metadata'?: Array<QrCodeGenerateQrCodeRequestMetadataInner>;
}

