/*
Developer API

At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface QrCodeGenerateQrCodeRequestMetadataInner
 */
export interface QrCodeGenerateQrCodeRequestMetadataInner {
    /**
     * The name of the custom field.
     * @type {string}
     * @memberof QrCodeGenerateQrCodeRequestMetadataInner
     */
    'name'?: string;
    /**
     * The value of the custom field.
     * @type {string}
     * @memberof QrCodeGenerateQrCodeRequestMetadataInner
     */
    'value'?: string;
}

