/*
Developer API

At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The destination bank account. Required if method is STANDARD.
 * @export
 * @interface RecipientCreateWithdrawalRequestBankAccount
 */
export interface RecipientCreateWithdrawalRequestBankAccount {
    /**
     * The type of bank account. Can be CHEKING or SAVINGS.
     * @type {string}
     * @memberof RecipientCreateWithdrawalRequestBankAccount
     */
    'type'?: RecipientCreateWithdrawalRequestBankAccountTypeEnum;
    /**
     * The name of the person or business that owns the bank account.
     * @type {string}
     * @memberof RecipientCreateWithdrawalRequestBankAccount
     */
    'holderName': string;
    /**
     * The tax ID of the account holder (CPF for individual account holders or CNPJ for businesses account holders).
     * @type {string}
     * @memberof RecipientCreateWithdrawalRequestBankAccount
     */
    'holderTaxId': string;
    /**
     * The type of entity that holds the account. Can be INDIVIDUAL or COMPANY.
     * @type {string}
     * @memberof RecipientCreateWithdrawalRequestBankAccount
     */
    'holderType': RecipientCreateWithdrawalRequestBankAccountHolderTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof RecipientCreateWithdrawalRequestBankAccount
     */
    'branchNumber': string;
    /**
     * 
     * @type {string}
     * @memberof RecipientCreateWithdrawalRequestBankAccount
     */
    'accountNumber': string;
    /**
     * The ID of the bank associated with the account.
     * @type {string}
     * @memberof RecipientCreateWithdrawalRequestBankAccount
     */
    'bankId': string;
}

type RecipientCreateWithdrawalRequestBankAccountTypeEnum = 'CHECKING' | 'SAVINGS'
type RecipientCreateWithdrawalRequestBankAccountHolderTypeEnum = 'INDIVIDUAL' | 'COMPANY'


