/*
Developer API

At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TokenGenerateAccessTokenRequest
 */
export interface TokenGenerateAccessTokenRequest {
    /**
     * The Refresh Token is used to get a new Access Token, when the old one expires.
     * @type {string}
     * @memberof TokenGenerateAccessTokenRequest
     */
    'refreshToken': string;
}

